---
title: "Portfolio 3: Preparing Dataset"
Date: "04/22/2025"
output: github_document
---

The goal of this and the proceeding portfolio pieces will be to rerun my thesis project using R. Therefore, this first project will detail the steps to transform the the .sav datasets I used in SPSS to .rds files. 

```{r camewithdoc, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}

library(haven) # necessary to read SPSS .sav files
library(readxl) # to read excel files

thesis_data <- read_sav("main_analysis_data.sav")

secondary_data <- read_sav("exploratory_data.sav")

life_event_data <- read_sav("life_event_prescreen.sav")

demographic_data <- read_excel("demographic_data.xlsx")

```

## Exploring the Data

```{r first_verify, include=FALSE}

str(thesis_data)

head(thesis_data)

names(thesis_data)

summary(thesis_data)

```

```{r second_verify, include = FALSE}

str(secondary_data)
summary(secondary_data)
head(secondary_data)
names(secondary_data)

```

```{r third_verify, include = FALSE}

str(life_event_data)
summary(life_event_data)
head(life_event_data)
names(life_event_data)

```

```{r fourth_verify, include = FALSE}

str(demographic_data)
summary(demographic_data)
head(demographic_data)
names(demographic_data)

```



```{r cleaning_up}

saveRDS(thesis_data, "thesis_data.rds")
saveRDS(secondary_data, "secondary_data.rds")
saveRDS(life_event_data, "life_event_data.rds")
saveRDS(demographic_data, "demographic_data.rds")

```

Okay now that all the data looks good and has been saved in a .rds format I should be able to rerun all the thesis analyses in Rstudio!
